### ISSUE TITLE
1주차과제

### ISSUE THREAD

**Issue by choi1204** [choi1204/Java_Study#1]
<h2>학습내용</h2>

- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이
- Garbage Collector은 무엇이고, Parallel GC와 CMS GC, G1 GC의 큰 차이는 무엇인지 설명해주세요. (mark-sweep-compact, concurrency-sweep, garbage-first)
- Java Reflection이란 무엇이고, 어떨 때 사용되는 것인가요?

**Comment by JDDng** [comment]
https://jddng.tistory.com/56

**Comment by choi1204** [comment]
https://night-hourglass-236.notion.site/1-a32bc1c0d65449fdae4c6c208609abe5

**Comment by SoYeon1333** [comment]
https://opalescent-saguaro-36f.notion.site/WEEK-1-JAVA-SE-d6b4612e07fc43a9b21222de8b467716

**Comment by Leejaeman** [comment]
https://profecessorleejaeman.tistory.com/entry/1%EC%A3%BC%EC%B0%A8

**Comment by tkdals5846** [comment]
https://ansm.tistory.com/2

**Comment by KDG-is** [comment]
https://kdg-is.tistory.com/entry/JAVA-JVM%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80

https://kdg-is.tistory.com/entry/JAVA-Garbage-Collection%EC%9D%B4%EB%9E%80

https://kdg-is.tistory.com/entry/JAVA-%EB%A6%AC%ED%94%8C%EB%A0%89%EC%85%98-Reflection%EC%9D%B4%EB%9E%80
